version: "3.8"


services:

  node_builder:
    container_name: node_builder
    image: "node:14"
    working_dir: /home/node/app
    volumes:
      - ./app/:/home/node/app


    command: sh -c "rm -r dist -f && rm -r api/dist -f && npm run build_front && npm run build_back"